apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: django
    tier: app

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: app
    spec:
      volumes:
        - name: django-app-data
          persistentVolumeClaim:
            claimName: django-app-pvc
      containers:
        - image: 977099002548.dkr.ecr.us-east-1.amazonaws.com/django-k8s-app:latest
          #imagePullPolicy: Never # Avoid the image to be pulled from dockerhub since it was pushed to Minikube
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          name: app
          ports:
            - containerPort: 8080
              name: app
          volumeMounts:
            - name: django-app-data
              mountPath: /vol/web
          env:
            - name: DB_HOST
              #value: django-postgres
              value: django-k8s-db.cels4u640btp.us-east-1.rds.amazonaws.com
            - name: DB_NAME
              #value: djangodb
              value: djangoproject
            - name: DB_USER
              value: djangouser
            - name: ALLOWED_HOSTS
              value: '127.0.0.1,localhost'
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret

        #- image: django-proxy:latest
        - image: 977099002548.dkr.ecr.us-east-1.amazonaws.com/django-k8s-proxy:latest
          #imagePullPolicy: Never
          name: proxy
          ports:
            - containerPort: 8000
              name: proxy
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: django-app-data
              mountPath: /vol/web
          env:
            - name: APP_HOST
              value: '127.0.0.1'
            - name: APP_PORT
              value: '8080'
